version: '3'

services:
  the_seed_homepage:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: the-seed-homepage
    volumes:
      - ../homepage:/home/node/app
    user: node
    stdin_open: true
    ports:
      - 8080:8080